import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CountriesService {
  countries = [
  {nom: "Afghanistan", code: "+93", longueur: 9},
  {nom: "Afrique du Sud", code: "+27", longueur: 9},
  {nom: "Albanie", code: "+355", longueur: 9},
  {nom: "Algérie", code: "+213", longueur: 9},
  {nom: "Allemagne", code: "+49", longueur: 10},
  {nom: "Andorre", code: "+376", longueur: 6},
  {nom: "Angola", code: "+244", longueur: 9},
  {nom: "Antigua-et-Barbuda", code: "+1", longueur: 10},
  {nom: "Arabie Saoudite", code: "+966", longueur: 9},
  {nom: "Argentine", code: "+54", longueur: 10},
  {nom: "Arménie", code: "+374", longueur: 8},
  {nom: "Australie", code: "+61", longueur: 9},
  {nom: "Autriche", code: "+43", longueur: 10},
  {nom: "Azerbaïdjan", code: "+994", longueur: 9},
  {nom: "Bahamas", code: "+1", longueur: 10},
  {nom: "Bahreïn", code: "+973", longueur: 8},
  {nom: "Bangladesh", code: "+880", longueur: 10},
  {nom: "Barbade", code: "+1", longueur: 10},
  {nom: "Belgique", code: "+32", longueur: 9},
  {nom: "Belize", code: "+501", longueur: 7},
  {nom: "Bénin", code: "+229", longueur: 8},
  {nom: "Bhoutan", code: "+975", longueur: 8},
  {nom: "Biélorussie", code: "+375", longueur: 9},
  {nom: "Birmanie", code: "+95", longueur: 9},
  {nom: "Bolivie", code: "+591", longueur: 8},
  {nom: "Bosnie-Herzégovine", code: "+387", longueur: 8},
  {nom: "Botswana", code: "+267", longueur: 8},
  {nom: "Brésil", code: "+55", longueur: 10},
  {nom: "Brunei", code: "+673", longueur: 7},
  {nom: "Bulgarie", code: "+359", longueur: 9},
  {nom: "Burkina Faso", code: "+226", longueur: 8},
  {nom: "Burundi", code: "+257", longueur: 8},
  {nom: "Cambodge", code: "+855", longueur: 9},
  {nom: "Cameroun", code: "+237", longueur: 9},
  {nom: "Canada", code: "+1", longueur: 10},
  {nom: "Cap-Vert", code: "+238", longueur: 7},
  {nom: "Chili", code: "+56", longueur: 9},
  {nom: "Chine", code: "+86", longueur: 11},
  {nom: "Chypre", code: "+357", longueur: 8},
  {nom: "Colombie", code: "+57", longueur: 10},
  {nom: "Comores", code: "+269", longueur: 7},
  {nom: "Congo", code: "+242", longueur: 9},
  {nom: "Corée du Nord", code: "+850", longueur: 12},
  {nom: "Corée du Sud", code: "+82", longueur: 10},
  {nom: "Costa Rica", code: "+506", longueur: 8},
  {nom: "Côte d'Ivoire", code: "+225", longueur: 8},
  {nom: "Croatie", code: "+385", longueur: 9},
  {nom: "Cuba", code: "+53", longueur: 8},
  {nom: "Danemark", code: "+45", longueur: 8},
  {nom: "Djibouti", code: "+253", longueur: 8},
  {nom: "Dominique", code: "+1", longueur: 10},
  {nom: "Égypte", code: "+20", longueur: 10},
  {nom: "Émirats arabes unis", code: "+971", longueur: 9},
  {nom: "Équateur", code: "+593", longueur: 9},
  {nom: "Érythrée", code: "+291", longueur: 7},
  {nom: "Espagne", code: "+34", longueur: 9},
  {nom: "Estonie", code: "+372", longueur: 8},
  {nom: "Eswatini", code: "+268", longueur: 8},
  {nom: "États-Unis", code: "+1", longueur: 10},
  {nom: "Éthiopie", code: "+251", longueur: 9},
  {nom: "Fidji", code: "+679", longueur: 7},
  {nom: "Finlande", code: "+358", longueur: 9},
  {nom: "France", code: "+33", longueur: 9},
  {nom: "Gabon", code: "+241", longueur: 7},
  {nom: "Gambie", code: "+220", longueur: 7},
  {nom: "Géorgie", code: "+995", longueur: 9},
  {nom: "Ghana", code: "+233", longueur: 9},
  {nom: "Grèce", code: "+30", longueur: 10},
  {nom: "Grenade", code: "+1", longueur: 10},
  {nom: "Guatemala", code: "+502", longueur: 8},
  {nom: "Guinée", code: "+224", longueur: 8},
  {nom: "Guinée équatoriale", code: "+240", longueur: 9},
  {nom: "Guinée-Bissau", code: "+245", longueur: 7},
  {nom: "Guyana", code: "+592", longueur: 7},
  {nom: "Haïti", code: "+509", longueur: 8},
  {nom: "Honduras", code: "+504", longueur: 8},
  {nom: "Hongrie", code: "+36", longueur: 9},
  {nom: "Inde", code: "+91", longueur: 10},
  {nom: "Indonésie", code: "+62", longueur: 10},
  {nom: "Irak", code: "+964", longueur: 10},
  {nom: "Iran", code: "+98", longueur: 10},
  {nom: "Irlande", code: "+353", longueur: 9},
  {nom: "Islande", code: "+354", longueur: 7},
  {nom: "Israël", code: "+972", longueur: 9},
  {nom: "Italie", code: "+39", longueur: 10},
  {nom: "Jamaïque", code: "+1", longueur: 10},
  {nom: "Japon", code: "+81", longueur: 10},
  {nom: "Jordanie", code: "+962", longueur: 9},
  {nom: "Kazakhstan", code: "+7", longueur: 10},
  {nom: "Kenya", code: "+254", longueur: 9},
  {nom: "Kirghizistan", code: "+996", longueur: 9},
  {nom: "Kiribati", code: "+686", longueur: 5},
  {nom: "Koweït", code: "+965", longueur: 8},
  {nom: "Laos", code: "+856", longueur: 10},
]
  constructor() { }




}
